import React from 'react';
import {Provider} from 'react-redux';
import {createStore} from 'redux';
import reducer from './src/reducers/index';
import StackNavigator from './src/routes/StackNavigator';

const initialState = {
  links: {
    next: null,
    previous: null,
  },
  count: 4,
  total_pages: 1,
  results: [
    {
      user: 'Daniel Rivera',
      created: '2020-12-11T18:54:52.410389-03:00',
      producer: {
        first_name: 'Daniel',
        last_name: 'Rivera',
        date_birth: '1991-11-07',
        document: '37164558',
        gender: 'Hombre',
        phone_number: '3837436534',
        producer_home: {
          district: 'Tinogasta, Centro',
          address: '50 viviendas los Robledos',
          type_recidence: 'Casa de ladrillo',
          state_recidence: 'Buen Estado',
        },
        producer_person: [
          {
            family_relation: 'Hijo',
            first_name: 'nombre hijo',
            last_name: 'apellido hijo',
            age: 2,
            has_primary_studies: true,
            has_secondary_studies: false,
            has_tertiary_studies: false,
            has_university_studies: false,
            perform_work_activity: false,
            description: 'Ninguna',
          },
          {
            family_relation: 'Esposa',
            first_name: 'nombre usuario',
            last_name: 'apellido usuario',
            age: 28,
            has_primary_studies: true,
            has_secondary_studies: true,
            has_tertiary_studies: false,
            has_university_studies: false,
            perform_work_activity: true,
            description: 'venta de artesanias ceramicas',
          },
        ],
        producer_vehicle: [
          {
            name_vehicle: 'Camioneta',
            use_trailer: false,
            type_trailer: 'Ninguno',
            use_semitrailer: false,
          },
          {
            name_vehicle: 'Camion',
            use_trailer: true,
            type_trailer: 'Ninguno',
            use_semitrailer: true,
          },
        ],
        producer_activity: {
          is_informal_worker: false,
          is_formal_worker: true,
          works_under_dependency: true,
          is_monotributista: true,
          category: 'C',
          use_external_labor: true,
          activity_worker: [
            {
              type_person: 'Trabajador',
              is_resident: false,
              gender: 'Hombre',
              receive_remuneration: true,
              work_position: 'Jefe',
              type_job: 'Transitorio',
            },
          ],
        },
        production: [
          {
            is_resident: true,
            district: 'La villa',
            surface: 10000,
            road_state: 'Buen Estado',
            lat: -28.06342,
            lng: -67.550457,
            has_renspa: true,
            production_property: {
              land_tenure: 'Propietario',
              has_land_title: true,
              cadastre_registration: '123456',
              starting_number: '1234567890',
            },
            production_service: {
              has_service_aqua: true,
              type_service_aqua: 'Red',
              has_service_energy: true,
              type_service_energy: 'Red electrica',
              has_rural_energy: false,
              has_generator: true,
              has_hydraulic_generator: false,
              has_solar_panels: false,
            },
            production_installation: {
              has_windmills: true,
              has_australian_tanks: true,
              has_dams: true,
              has_truck_scale: true,
              has_fire_break: true,
              has_minced_steel: true,
              has_pools: true,
              installation_barn: [
                {
                  surface: 1000,
                  lat: -28.058649,
                  lng: -67.560242,
                },
                {
                  surface: 2000,
                  lat: -28.0588,
                  lng: -67.557667,
                },
              ],
              installation_well: [
                {
                  is_active: true,
                  lat: -28.051983,
                  lng: -67.558697,
                },
                {
                  is_active: false,
                  lat: -28.051907,
                  lng: -67.561787,
                },
              ],
            },
            production_machine: [
              {
                destination: 'Producción Agricola',
                name_machine: 'Tractor',
                type_maquinary: 'Propia',
                model: '94',
                state_machine: 'Regular',
                age: '6',
                observation: 'ninguna',
              },
            ],
            production_irrigation: {
              type_irrigation: 'Presurizado',
              pressurized_irrigation: 'Goteo',
              surface_irrigation: 'Caracol',
              take_section: 'seccion 1',
              watering_hours: 5,
              channel_conditions: 'Bueno',
              right: 'Agua',
              shifts: 'Largos',
            },
            production_agricultural: [
              {
                name: 'Agricola',
                activity_name: 'Siembra de tomates',
                surface: 1000,
                destination: 'consumo propio',
                sowing: 'siembra',
                type_sowing: 'anual',
                age: 1,
                problems: 'Ninguno',
                suggestion: 'Ninguna sugerencia',
                agricultural_attendance: {
                  use_fertilizers: true,
                  use_food_organic: true,
                  use_pheromones: true,
                  use_hail_mesh: true,
                  make_frost_control: true,
                  other_practices: 'Otras Practicas',
                },
                agricultural_climatic: {
                  factor: 'Escarchas',
                  risk: 'Medio',
                  damange_level: 'Bajo',
                },
                agricultural_pests: [
                  {
                    type_pests: 'Plaga',
                    pests_description: 'Descripcion de la plaga',
                    make_pests_control: true,
                    make_pesticide: false,
                    type_pesticide: 'Tipo de Pesticida',
                    other_practices: 'Se realizan otras practicas',
                  },
                  {
                    type_pests: 'Enfermedad',
                    pests_description: 'Descripcion de la enfermedad',
                    make_pests_control: true,
                    make_pesticide: false,
                    type_pesticide: 'Tipo de Pesticida',
                    other_practices: 'Se realizan otras practicas',
                  },
                ],
                agricultural_harvest: {
                  harvest_surface: 5000,
                  tons_production: 2000,
                  has_curtains_insulated: false,
                  plant_length_curtains: 150,
                  plant_species_curtains: 'Plantas',
                  harvest_time: 'meses de cocecha',
                },
                agricultural_sales_channel: {
                  is_collector: true,
                  is_cooperative: true,
                  is_exporter: true,
                  use_baler: true,
                  use_fair: true,
                  use_industry: true,
                  use_fridge: true,
                },
              },
            ],
            production_livestock: [
              {
                name: 'Ganadera',
                type_activity: 'vovinos',
                surface: 20000,
                destination: 'Consumo',
                make_technical_assistance: true,
                problems: 'Sin problemas',
                suggestion: 'Ninguno',
                livestock_animal_feeding: [
                  {
                    feeding: 'alfa',
                    type_feeding: 'Naturales',
                    daily_rations: 5.5,
                  },
                ],
                livestock_reproduction: {
                  make_reproductive_management: true,
                  make_continuous_service: true,
                  make_corral_service: true,
                  make_artificial_insemination: true,
                  make_embryo_transplant: true,
                  other_practices: 'Otras Practicas',
                },
                livestock_animal_pens: [
                  {
                    orientation: 'Norte',
                    building_material: 'Madera, Alambre',
                    roof_material: 'Ninguno',
                    foor_material: 'Contrapizo',
                    surface: 25,
                    num_animals: 5,
                    lat: -26.234423,
                    lng: -48.453444,
                  },
                ],
                livestock_health: {
                  type_technical_assistance: 'Privada',
                  vitamin_complex: 'Complejo vitaminico',
                  make_internal_deworming: true,
                  make_external_deworming: true,
                  type_antiparasitic: 'Tipo de antiparasitario',
                  make_vaccination: true,
                  type_vaccination: 'Anual',
                  type_disease: 'Zoonoticas',
                  other_practices: 'No hay otras practicas',
                },
                livestock_marketing: {
                  number_slaughtered: 150,
                  number_shorn: 150,
                  amount_wool_hair: 100,
                  amount_leather: 70,
                  liters_milk: 500,
                  milk_destination: 'Destino de leche',
                  wool_hair_destination: 'Destino de pelo lana',
                  leather_destination: 'Destino de piel',
                  slaughter_destination: 'Destino de Faenados',
                },
                livestock_sales_channel: {
                  is_collector: true,
                  is_cooperative: true,
                  is_exporter: true,
                  use_baler: true,
                  use_fair: true,
                  use_industry: true,
                  use_fridge: true,
                },
                livestock_bovine_cycle: {
                  calves_under_one_year: 1,
                  heifers_one_to_two_years: 1,
                  heifers_over_two_years: 1,
                  number_cows: 1,
                  steers_one_to_two_years: 1,
                  steers_older_two_years: 1,
                  bulls_one_to_two_years: 1,
                  bulls_older_two_years: 1,
                  number_oxen_torunos: 1,
                },
                livestock_sheep_cycle: {
                  sheep_under_six_months: 1,
                  sheep_older_six_months_to_calving: 1,
                  sheep_older_six_months_one_year: 1,
                  number_sheep: 1,
                  number_capons: 1,
                  number_rams: 1,
                },
                livestock_goat_cycle: {
                  goats_under_six_months: 1,
                  goats_six_months_to_first_calving: 1,
                  number_goats: 1,
                  number_capons: 1,
                  number_stallions: 1,
                },
                livestock_pig_cycle: {
                  up_two_months: 1,
                  older_two_months: 1,
                  less_four_months: 1,
                  older_four_months: 1,
                  number_pigs: 1,
                  number_stallions: 1,
                },
                livestock_llama_cycle: {
                  number_chitas_teques: 1,
                  number_maltones: 1,
                  number_janachos: 1,
                  number_llamas_mothers: 1,
                  number_capons: 1,
                },
                livestock_poultry_cycle: {
                  is_intensive_poultry: true,
                  number_broilers_incubated: 1,
                  breeding_males: 1,
                  number_eggs_chickens_babies: 2,
                  number_incubators: 5,
                  number_broilers_fattening: 4,
                  number_breeding_layers: 2,
                  existence: 'Gallinas, Gallos, Pollos',
                },
                livestock_rabbit_cycle: {
                  orientation: 'Carne, Pelo',
                  number_breeding_males: 3,
                  number_breeding_females: 4,
                  number_rabbit: 7,
                },
                livestock_beekeeping_cycle: {
                  kind_bee: 'Tipo de abeja',
                  has_bee_hives: true,
                  type_bee_hives: 'Propias',
                  number_drawers: 5,
                  alsas_drawer: 10,
                  type_drawer: 'Fijos',
                  honey_stones: 20,
                  pollination_period:
                    'Septiembre, Octubre, Noviembre, Diciembre',
                  pollinated_flower: 'Tipo de flor polinizada',
                  has_renapa: true,
                },
                livestock_aquaculture_cycle: {
                  orientation: 'Cria',
                  existence: 'Pacu',
                },
              },
            ],
            production_agroindustrial: [
              {
                description: 'venta de artesanias ceramicas',
                type_agribusiness: 'Artesanal',
                is_mechanized: true,
                agroindustrial_tools: [
                  {
                    name_tool: 'Torno Electrico',
                    type_tool: 'Electrico Artesanal',
                    number_tools: 1,
                  },
                ],
                agroindustrial_food_product: [
                  {
                    name_product: 'Rosquitas',
                    validity: 'Poco',
                    price: 200,
                  },
                ],
                agroindustrial_handmande_product: [
                  {
                    name_product: 'Plato',
                    quantity: 2,
                    price: 50,
                  },
                ],
              },
            ],
          },
        ],
      },
    },
    {
      user: 'Walter Tapia',
      created: '2020-12-11T18:54:52.349744-03:00',
      producer: {
        first_name: 'Walter',
        last_name: 'Tapia',
        date_birth: '1991-11-07',
        document: '35565858',
        gender: 'Hombre',
        phone_number: '3837436534',
        producer_home: {
          district: 'Tinogasta, Centro',
          address: 'Barrio Progreso',
          type_recidence: 'Casa de ladrillo',
          state_recidence: 'Buen Estado',
        },
        producer_person: [
          {
            family_relation: 'Hijo',
            first_name: 'nombre hijo',
            last_name: 'apellido hijo',
            age: 2,
            has_primary_studies: true,
            has_secondary_studies: false,
            has_tertiary_studies: false,
            has_university_studies: false,
            perform_work_activity: false,
            description: 'Ninguna',
          },
          {
            family_relation: 'Esposa',
            first_name: 'nombre usuario',
            last_name: 'apellido usuario',
            age: 28,
            has_primary_studies: true,
            has_secondary_studies: true,
            has_tertiary_studies: false,
            has_university_studies: false,
            perform_work_activity: true,
            description: 'venta de artesanias ceramicas',
          },
        ],
        producer_vehicle: [
          {
            name_vehicle: 'Camioneta',
            use_trailer: false,
            type_trailer: 'Ninguno',
            use_semitrailer: false,
          },
          {
            name_vehicle: 'Camion',
            use_trailer: true,
            type_trailer: 'Ninguno',
            use_semitrailer: true,
          },
        ],
        producer_activity: {
          is_informal_worker: false,
          is_formal_worker: true,
          works_under_dependency: true,
          is_monotributista: true,
          category: 'C',
          use_external_labor: true,
          activity_worker: [
            {
              type_person: 'Trabajador',
              is_resident: false,
              gender: 'Hombre',
              receive_remuneration: true,
              work_position: 'Jefe',
              type_job: 'Transitorio',
            },
          ],
        },
        production: [
          {
            is_resident: true,
            district: 'La villa',
            surface: 10000,
            road_state: 'Buen Estado',
            lat: -28.06342,
            lng: -67.550457,
            has_renspa: true,
            production_property: {
              land_tenure: 'Propietario',
              has_land_title: true,
              cadastre_registration: '123456',
              starting_number: '1234567890',
            },
            production_service: {
              has_service_aqua: true,
              type_service_aqua: 'Red',
              has_service_energy: true,
              type_service_energy: 'Red electrica',
              has_rural_energy: false,
              has_generator: true,
              has_hydraulic_generator: false,
              has_solar_panels: false,
            },
            production_installation: {
              has_windmills: true,
              has_australian_tanks: true,
              has_dams: true,
              has_truck_scale: true,
              has_fire_break: true,
              has_minced_steel: true,
              has_pools: true,
              installation_barn: [
                {
                  surface: 1000,
                  lat: -28.058649,
                  lng: -67.560242,
                },
                {
                  surface: 2000,
                  lat: -28.0588,
                  lng: -67.557667,
                },
              ],
              installation_well: [
                {
                  is_active: true,
                  lat: -28.051983,
                  lng: -67.558697,
                },
                {
                  is_active: false,
                  lat: -28.051907,
                  lng: -67.561787,
                },
              ],
            },
            production_machine: [
              {
                destination: 'Producción Agricola',
                name_machine: 'Tractor',
                type_maquinary: 'Propia',
                model: '94',
                state_machine: 'Regular',
                age: '6',
                observation: 'ninguna',
              },
            ],
            production_irrigation: {
              type_irrigation: 'Presurizado',
              pressurized_irrigation: 'Goteo',
              surface_irrigation: 'Caracol',
              take_section: 'seccion 1',
              watering_hours: 5,
              channel_conditions: 'Bueno',
              right: 'Agua',
              shifts: 'Largos',
            },
            production_agricultural: [
              {
                name: 'Agricola',
                activity_name: 'Siembra de tomates',
                surface: 1000,
                destination: 'consumo propio',
                sowing: 'siembra',
                type_sowing: 'anual',
                age: 1,
                problems: 'Ninguno',
                suggestion: 'Ninguna sugerencia',
                agricultural_attendance: {
                  use_fertilizers: true,
                  use_food_organic: true,
                  use_pheromones: true,
                  use_hail_mesh: true,
                  make_frost_control: true,
                  other_practices: 'Otras Practicas',
                },
                agricultural_climatic: {
                  factor: 'Escarchas',
                  risk: 'Medio',
                  damange_level: 'Bajo',
                },
                agricultural_pests: [
                  {
                    type_pests: 'Plaga',
                    pests_description: 'Descripcion de la plaga',
                    make_pests_control: true,
                    make_pesticide: false,
                    type_pesticide: 'Tipo de Pesticida',
                    other_practices: 'Se realizan otras practicas',
                  },
                  {
                    type_pests: 'Enfermedad',
                    pests_description: 'Descripcion de la enfermedad',
                    make_pests_control: true,
                    make_pesticide: false,
                    type_pesticide: 'Tipo de Pesticida',
                    other_practices: 'Se realizan otras practicas',
                  },
                ],
                agricultural_harvest: {
                  harvest_surface: 5000,
                  tons_production: 2000,
                  has_curtains_insulated: false,
                  plant_length_curtains: 150,
                  plant_species_curtains: 'Plantas',
                  harvest_time: 'meses de cocecha',
                },
                agricultural_sales_channel: {
                  is_collector: true,
                  is_cooperative: true,
                  is_exporter: true,
                  use_baler: true,
                  use_fair: true,
                  use_industry: true,
                  use_fridge: true,
                },
              },
            ],
            production_livestock: [
              {
                name: 'Ganadera',
                type_activity: 'vovinos',
                surface: 20000,
                destination: 'Consumo',
                make_technical_assistance: true,
                problems: 'Sin problemas',
                suggestion: 'Ninguno',
                livestock_animal_feeding: [
                  {
                    feeding: 'alfa',
                    type_feeding: 'Naturales',
                    daily_rations: 5.5,
                  },
                ],
                livestock_reproduction: {
                  make_reproductive_management: true,
                  make_continuous_service: true,
                  make_corral_service: true,
                  make_artificial_insemination: true,
                  make_embryo_transplant: true,
                  other_practices: 'Otras Practicas',
                },
                livestock_animal_pens: [
                  {
                    orientation: 'Norte',
                    building_material: 'Madera, Alambre',
                    roof_material: 'Ninguno',
                    foor_material: 'Contrapizo',
                    surface: 25,
                    num_animals: 5,
                    lat: -26.234423,
                    lng: -48.453444,
                  },
                ],
                livestock_health: {
                  type_technical_assistance: 'Privada',
                  vitamin_complex: 'Complejo vitaminico',
                  make_internal_deworming: true,
                  make_external_deworming: true,
                  type_antiparasitic: 'Tipo de antiparasitario',
                  make_vaccination: true,
                  type_vaccination: 'Anual',
                  type_disease: 'Zoonoticas',
                  other_practices: 'No hay otras practicas',
                },
                livestock_marketing: {
                  number_slaughtered: 150,
                  number_shorn: 150,
                  amount_wool_hair: 100,
                  amount_leather: 70,
                  liters_milk: 500,
                  milk_destination: 'Destino de leche',
                  wool_hair_destination: 'Destino de pelo lana',
                  leather_destination: 'Destino de piel',
                  slaughter_destination: 'Destino de Faenados',
                },
                livestock_sales_channel: {
                  is_collector: true,
                  is_cooperative: true,
                  is_exporter: true,
                  use_baler: true,
                  use_fair: true,
                  use_industry: true,
                  use_fridge: true,
                },
                livestock_bovine_cycle: {
                  calves_under_one_year: 1,
                  heifers_one_to_two_years: 1,
                  heifers_over_two_years: 1,
                  number_cows: 1,
                  steers_one_to_two_years: 1,
                  steers_older_two_years: 1,
                  bulls_one_to_two_years: 1,
                  bulls_older_two_years: 1,
                  number_oxen_torunos: 1,
                },
                livestock_sheep_cycle: {
                  sheep_under_six_months: 1,
                  sheep_older_six_months_to_calving: 1,
                  sheep_older_six_months_one_year: 1,
                  number_sheep: 1,
                  number_capons: 1,
                  number_rams: 1,
                },
                livestock_goat_cycle: {
                  goats_under_six_months: 1,
                  goats_six_months_to_first_calving: 1,
                  number_goats: 1,
                  number_capons: 1,
                  number_stallions: 1,
                },
                livestock_pig_cycle: {
                  up_two_months: 1,
                  older_two_months: 1,
                  less_four_months: 1,
                  older_four_months: 1,
                  number_pigs: 1,
                  number_stallions: 1,
                },
                livestock_llama_cycle: {
                  number_chitas_teques: 1,
                  number_maltones: 1,
                  number_janachos: 1,
                  number_llamas_mothers: 1,
                  number_capons: 1,
                },
                livestock_poultry_cycle: {
                  is_intensive_poultry: true,
                  number_broilers_incubated: 1,
                  breeding_males: 1,
                  number_eggs_chickens_babies: 2,
                  number_incubators: 5,
                  number_broilers_fattening: 4,
                  number_breeding_layers: 2,
                  existence: 'Gallinas, Gallos, Pollos',
                },
                livestock_rabbit_cycle: {
                  orientation: 'Carne, Pelo',
                  number_breeding_males: 3,
                  number_breeding_females: 4,
                  number_rabbit: 7,
                },
                livestock_beekeeping_cycle: {
                  kind_bee: 'Tipo de abeja',
                  has_bee_hives: true,
                  type_bee_hives: 'Propias',
                  number_drawers: 5,
                  alsas_drawer: 10,
                  type_drawer: 'Fijos',
                  honey_stones: 20,
                  pollination_period:
                    'Septiembre, Octubre, Noviembre, Diciembre',
                  pollinated_flower: 'Tipo de flor polinizada',
                  has_renapa: true,
                },
                livestock_aquaculture_cycle: {
                  orientation: 'Cria',
                  existence: 'Pacu',
                },
              },
            ],
            production_agroindustrial: [
              {
                description: 'venta de artesanias ceramicas',
                type_agribusiness: 'Artesanal',
                is_mechanized: true,
                agroindustrial_tools: [
                  {
                    name_tool: 'Torno Electrico',
                    type_tool: 'Electrico Artesanal',
                    number_tools: 1,
                  },
                ],
                agroindustrial_food_product: [
                  {
                    name_product: 'Rosquitas',
                    validity: 'Poco',
                    price: 200,
                  },
                ],
                agroindustrial_handmande_product: [
                  {
                    name_product: 'Plato',
                    quantity: 2,
                    price: 50,
                  },
                ],
              },
            ],
          },
        ],
      },
    },
    {
      user: 'Paola Cuello',
      created: '2020-12-11T18:43:00.847883-03:00',
      producer: {
        first_name: 'Paola',
        last_name: 'Cuello',
        date_birth: '1991-11-07',
        document: '35565858',
        gender: 'Mujer',
        phone_number: '3837436534',
        producer_home: {
          district: 'Tinogasta, Centro',
          address: 'Barrio Progreso',
          type_recidence: 'Casa de ladrillo',
          state_recidence: 'Buen Estado',
        },
        producer_person: [
          {
            family_relation: 'Hijo',
            first_name: 'nombre hijo',
            last_name: 'apellido hijo',
            age: 2,
            has_primary_studies: true,
            has_secondary_studies: false,
            has_tertiary_studies: false,
            has_university_studies: false,
            perform_work_activity: false,
            description: 'Ninguna',
          },
          {
            family_relation: 'Esposa',
            first_name: 'nombre usuario',
            last_name: 'apellido usuario',
            age: 28,
            has_primary_studies: true,
            has_secondary_studies: true,
            has_tertiary_studies: false,
            has_university_studies: false,
            perform_work_activity: true,
            description: 'venta de artesanias ceramicas',
          },
        ],
        producer_vehicle: [
          {
            name_vehicle: 'Camioneta',
            use_trailer: false,
            type_trailer: 'Ninguno',
            use_semitrailer: false,
          },
          {
            name_vehicle: 'Camion',
            use_trailer: true,
            type_trailer: 'Ninguno',
            use_semitrailer: true,
          },
        ],
        producer_activity: {
          is_informal_worker: false,
          is_formal_worker: true,
          works_under_dependency: true,
          is_monotributista: true,
          category: 'C',
          use_external_labor: true,
          activity_worker: [
            {
              type_person: 'Trabajador',
              is_resident: false,
              gender: 'Hombre',
              receive_remuneration: true,
              work_position: 'Jefe',
              type_job: 'Transitorio',
            },
          ],
        },
        production: [
          {
            is_resident: true,
            district: 'La villa',
            surface: 10000,
            road_state: 'Buen Estado',
            lat: -28.06342,
            lng: -67.550457,
            has_renspa: true,
            production_property: {
              land_tenure: 'Propietario',
              has_land_title: true,
              cadastre_registration: '123456',
              starting_number: '1234567890',
            },
            production_service: {
              has_service_aqua: true,
              type_service_aqua: 'Red',
              has_service_energy: true,
              type_service_energy: 'Red electrica',
              has_rural_energy: false,
              has_generator: true,
              has_hydraulic_generator: false,
              has_solar_panels: false,
            },
            production_installation: {
              has_windmills: true,
              has_australian_tanks: true,
              has_dams: true,
              has_truck_scale: true,
              has_fire_break: true,
              has_minced_steel: true,
              has_pools: true,
              installation_barn: [
                {
                  surface: 1000,
                  lat: -28.058649,
                  lng: -67.560242,
                },
                {
                  surface: 2000,
                  lat: -28.0588,
                  lng: -67.557667,
                },
              ],
              installation_well: [
                {
                  is_active: true,
                  lat: -28.051983,
                  lng: -67.558697,
                },
                {
                  is_active: false,
                  lat: -28.051907,
                  lng: -67.561787,
                },
              ],
            },
            production_machine: [
              {
                destination: 'Producción Agricola',
                name_machine: 'Tractor',
                type_maquinary: 'Propia',
                model: '94',
                state_machine: 'Regular',
                age: '6',
                observation: 'ninguna',
              },
            ],
            production_irrigation: {
              type_irrigation: 'Presurizado',
              pressurized_irrigation: 'Goteo',
              surface_irrigation: 'Caracol',
              take_section: 'seccion 1',
              watering_hours: 5,
              channel_conditions: 'Bueno',
              right: 'Agua',
              shifts: 'Largos',
            },
            production_agricultural: [
              {
                name: 'Agricola',
                activity_name: 'Siembra de tomates',
                surface: 1000,
                destination: 'consumo propio',
                sowing: 'siembra',
                type_sowing: 'anual',
                age: 1,
                problems: 'Ninguno',
                suggestion: 'Ninguna sugerencia',
                agricultural_attendance: {
                  use_fertilizers: true,
                  use_food_organic: true,
                  use_pheromones: true,
                  use_hail_mesh: true,
                  make_frost_control: true,
                  other_practices: 'Otras Practicas',
                },
                agricultural_climatic: {
                  factor: 'Escarchas',
                  risk: 'Medio',
                  damange_level: 'Bajo',
                },
                agricultural_pests: [
                  {
                    type_pests: 'Plaga',
                    pests_description: 'Descripcion de la plaga',
                    make_pests_control: true,
                    make_pesticide: false,
                    type_pesticide: 'Tipo de Pesticida',
                    other_practices: 'Se realizan otras practicas',
                  },
                  {
                    type_pests: 'Enfermedad',
                    pests_description: 'Descripcion de la enfermedad',
                    make_pests_control: true,
                    make_pesticide: false,
                    type_pesticide: 'Tipo de Pesticida',
                    other_practices: 'Se realizan otras practicas',
                  },
                ],
                agricultural_harvest: {
                  harvest_surface: 5000,
                  tons_production: 2000,
                  has_curtains_insulated: false,
                  plant_length_curtains: 150,
                  plant_species_curtains: 'Plantas',
                  harvest_time: 'meses de cocecha',
                },
                agricultural_sales_channel: {
                  is_collector: true,
                  is_cooperative: true,
                  is_exporter: true,
                  use_baler: true,
                  use_fair: true,
                  use_industry: true,
                  use_fridge: true,
                },
              },
            ],
            production_livestock: [
              {
                name: 'Ganadera',
                type_activity: 'vovinos',
                surface: 20000,
                destination: 'Consumo',
                make_technical_assistance: true,
                problems: 'Sin problemas',
                suggestion: 'Ninguno',
                livestock_animal_feeding: [
                  {
                    feeding: 'alfa',
                    type_feeding: 'Naturales',
                    daily_rations: 5.5,
                  },
                ],
                livestock_reproduction: {
                  make_reproductive_management: true,
                  make_continuous_service: true,
                  make_corral_service: true,
                  make_artificial_insemination: true,
                  make_embryo_transplant: true,
                  other_practices: 'Otras Practicas',
                },
                livestock_animal_pens: [
                  {
                    orientation: 'Norte',
                    building_material: 'Madera, Alambre',
                    roof_material: 'Ninguno',
                    foor_material: 'Contrapizo',
                    surface: 25,
                    num_animals: 5,
                    lat: -26.234423,
                    lng: -48.453444,
                  },
                ],
                livestock_health: {
                  type_technical_assistance: 'Privada',
                  vitamin_complex: 'Complejo vitaminico',
                  make_internal_deworming: true,
                  make_external_deworming: true,
                  type_antiparasitic: 'Tipo de antiparasitario',
                  make_vaccination: true,
                  type_vaccination: 'Anual',
                  type_disease: 'Zoonoticas',
                  other_practices: 'No hay otras practicas',
                },
                livestock_marketing: {
                  number_slaughtered: 150,
                  number_shorn: 150,
                  amount_wool_hair: 100,
                  amount_leather: 70,
                  liters_milk: 500,
                  milk_destination: 'Destino de leche',
                  wool_hair_destination: 'Destino de pelo lana',
                  leather_destination: 'Destino de piel',
                  slaughter_destination: 'Destino de Faenados',
                },
                livestock_sales_channel: {
                  is_collector: true,
                  is_cooperative: true,
                  is_exporter: true,
                  use_baler: true,
                  use_fair: true,
                  use_industry: true,
                  use_fridge: true,
                },
                livestock_bovine_cycle: {
                  calves_under_one_year: 1,
                  heifers_one_to_two_years: 1,
                  heifers_over_two_years: 1,
                  number_cows: 1,
                  steers_one_to_two_years: 1,
                  steers_older_two_years: 1,
                  bulls_one_to_two_years: 1,
                  bulls_older_two_years: 1,
                  number_oxen_torunos: 1,
                },
                livestock_sheep_cycle: {
                  sheep_under_six_months: 1,
                  sheep_older_six_months_to_calving: 1,
                  sheep_older_six_months_one_year: 1,
                  number_sheep: 1,
                  number_capons: 1,
                  number_rams: 1,
                },
                livestock_goat_cycle: {
                  goats_under_six_months: 1,
                  goats_six_months_to_first_calving: 1,
                  number_goats: 1,
                  number_capons: 1,
                  number_stallions: 1,
                },
                livestock_pig_cycle: {
                  up_two_months: 1,
                  older_two_months: 1,
                  less_four_months: 1,
                  older_four_months: 1,
                  number_pigs: 1,
                  number_stallions: 1,
                },
                livestock_llama_cycle: {
                  number_chitas_teques: 1,
                  number_maltones: 1,
                  number_janachos: 1,
                  number_llamas_mothers: 1,
                  number_capons: 1,
                },
                livestock_poultry_cycle: {
                  is_intensive_poultry: true,
                  number_broilers_incubated: 1,
                  breeding_males: 1,
                  number_eggs_chickens_babies: 2,
                  number_incubators: 5,
                  number_broilers_fattening: 4,
                  number_breeding_layers: 2,
                  existence: 'Gallinas, Gallos, Pollos',
                },
                livestock_rabbit_cycle: {
                  orientation: 'Carne, Pelo',
                  number_breeding_males: 3,
                  number_breeding_females: 4,
                  number_rabbit: 7,
                },
                livestock_beekeeping_cycle: {
                  kind_bee: 'Tipo de abeja',
                  has_bee_hives: true,
                  type_bee_hives: 'Propias',
                  number_drawers: 5,
                  alsas_drawer: 10,
                  type_drawer: 'Fijos',
                  honey_stones: 20,
                  pollination_period:
                    'Septiembre, Octubre, Noviembre, Diciembre',
                  pollinated_flower: 'Tipo de flor polinizada',
                  has_renapa: true,
                },
                livestock_aquaculture_cycle: {
                  orientation: 'Cria',
                  existence: 'Pacu',
                },
              },
            ],
            production_agroindustrial: [
              {
                description: 'venta de artesanias ceramicas',
                type_agribusiness: 'Artesanal',
                is_mechanized: true,
                agroindustrial_tools: [
                  {
                    name_tool: 'Torno Electrico',
                    type_tool: 'Electrico Artesanal',
                    number_tools: 1,
                  },
                ],
                agroindustrial_food_product: [
                  {
                    name_product: 'Rosquitas',
                    validity: 'Poco',
                    price: 200,
                  },
                ],
                agroindustrial_handmande_product: [
                  {
                    name_product: 'Plato',
                    quantity: 2,
                    price: 50,
                  },
                ],
              },
            ],
          },
        ],
      },
    },
  ],
};

const store = createStore(reducer, initialState);

const App = () => {
  return (
    <Provider store={store}>
      <StackNavigator />
    </Provider>
  );
};

export default App;
